[versions]
kotlin = "2.2.0"
moshi = "1.15.2"
pkl = "0.+"
antlr = "4.9.0"
spotlessPlugin = "6.21.0"

[libraries]
kotlinStdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk8", version.ref = "kotlin" }
moshiKotlin = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshi" }
pklParser = { group = "org.pkl-lang", name = "pkl-parser", version.ref = "pkl" }
pklCore = { group = "org.pkl-lang", name = "pkl-core", version.ref = "pkl" }
pklFormatter = { group = "org.pkl-lang", name = "pkl-formatter", version.ref = "pkl" }
antlr = { group = "com.tunnelvisionlabs", name = "antlr4-runtime", version.ref = "antlr" }

[plugins]
pkl = { id = "org.pkl-lang", version.ref = "pkl" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotlessPlugin"}
